Repository pagopa/pagopa-biz-pm-ingestion, pull requests merged in 2024-09, with the labels that each got.

#3 [PAGOPA-2101] fix debtor cf not valid
  openapi/openapi.json
  src/main/java/it/gov/pagopa/bizpmingestion/controller/IPMExtractionController.java
  src/main/java/it/gov/pagopa/bizpmingestion/controller/impl/PMExtractionController.java
  src/main/java/it/gov/pagopa/bizpmingestion/entity/cosmos/view/UserDetail.java
  src/main/java/it/gov/pagopa/bizpmingestion/entity/pm/PPPayPal.java
  src/main/java/it/gov/pagopa/bizpmingestion/entity/pm/PPPaymentDetail.java
  src/main/java/it/gov/pagopa/bizpmingestion/enumeration/PMExtractionType.java
  src/main/java/it/gov/pagopa/bizpmingestion/mapper/ConvertPPTransactionEntityToPMEvent.java
  src/main/java/it/gov/pagopa/bizpmingestion/model/DataExtractionOptionsModel.java
  src/main/java/it/gov/pagopa/bizpmingestion/model/pm/PMEventPayPal.java
  src/main/java/it/gov/pagopa/bizpmingestion/model/pm/PMEventPaymentDetail.java
  src/main/java/it/gov/pagopa/bizpmingestion/schedulingtasks/CardDataExtractionScheduledTask.java
  src/main/java/it/gov/pagopa/bizpmingestion/service/IPMEventToViewService.java
  src/main/java/it/gov/pagopa/bizpmingestion/service/impl/PMEventToViewServiceImpl.java
  src/main/java/it/gov/pagopa/bizpmingestion/service/impl/PMExtractionService.java
  src/main/java/it/gov/pagopa/bizpmingestion/util/PMEventViewValidator.java
  src/test/java/it/gov/pagopa/bizpmingestion/controller/PMExtractionControllerTest.java
  src/test/java/it/gov/pagopa/bizpmingestion/schedulingtasks/CardDataExtractionScheduledTaskTest.java
  src/test/java/it/gov/pagopa/bizpmingestion/specification/SpecificationTest.java
  src/test/java/it/gov/pagopa/bizpmingestion/util/Util.java
Labels: bug, patch

#5 Fix Deploy
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  openapi/openapi.json
  pom.xml
  src/main/java/it/gov/pagopa/bizpmingestion/config/OpenApiConfig.java
  src/main/java/it/gov/pagopa/bizpmingestion/controller/IPMExtractionController.java
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: patch

#6 feat: Add innfra
  .devops/performance-test-pipelines.yml
  .identity/.terraform.lock.hcl
  .opex/env/prod/backend.tfvars
  .opex/env/prod/config.yaml
  .opex/env/prod/terraform.tfvars
  CODEOWNERS
  README.md
  docker/docker-compose.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  infra/.terraform.lock.hcl
  infra/04_apim_api.tf
  infra/99_locals.tf
  infra/env/weu-dev/backend.tfvars
  infra/env/weu-dev/terraform.tfvars
  infra/env/weu-prod/backend.tfvars
  infra/env/weu-prod/terraform.tfvars
  infra/env/weu-uat/backend.tfvars
  infra/env/weu-uat/terraform.tfvars
  infra/policy/_base_policy.xml
  integration-test/src/package-lock.json
  integration-test/src/package.json
  openapi/openapi.json
  pom.xml
  postman-collection/README.md
  postman-collection/run_newman.sh
Labels: size/large, patch

#7 feat: [PagoPA-2110] - hidden field by origin
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/bizpmingestion/mapper/ConvertPPTransactionEntityToPMEvent.java
  src/main/java/it/gov/pagopa/bizpmingestion/service/impl/PMEventToViewServiceImpl.java
  src/test/java/it/gov/pagopa/bizpmingestion/service/PMEventToViewServiceTest.java
Labels: enhancement, size/small, patch
